# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-redshift-cluster
  description: Terraform module to provision an AWS Redshift Cluster
  homepage: https://cloudposse.com/accelerate
  topics: ""
